### ISSUE TITLE
Cannot pass json object to ctor

### ISSUE THREAD

**Issue by stefanrcint** [InteractiveAdvertisingBureau/iabtcf-es#99] opened 2020-03-09 19:19 UTC
**Version**
1.0.0-beta.19

**Module**
Core

**Describe the bug**
I have downloaded a v2 global vendor list and try to pass a deserialized version of that in the GVL constructor as an object, but it is apparently not recognized and the library instead asks me to provide a baseUrl. If doing so, an HTTP-request is attempted instead of using the provided object.

If i handcraft a vendor list object i get this exception instead:

```
     TypeError: Cannot read property 'then' of undefined
      at t.set [as gvl] (node_modules\@iabtcf\core\lib\TCModel.js:1:1450)
      at new t (node_modules\@iabtcf\core\lib\TCModel.js:1:1202)

```
My objective is to create a TCModel from an in-memory vendor list for unit testing purposes - i need to be able to controll purposes and vendors

**Steps to Reproduce**
Download a v2 global vendor list and store it.
JSON.parse it /load it with require(...) and pass it to the GVL constructor

OR

Manually construct a vendor list JSON object and pass it to the constructor

**Expected behavior**
A valid GVL (and subsequently a TCModel)

**Actual behavior**
An HTTP call is made to try to download a vendor list 
OR
An exception

**Comment by stefanrcint** [comment] 2020-03-12 08:51
Maybe there is just a need for guidance here, like a code example showing how to construct a VendorList json object that the GVL constructor will accept?

**Comment by chrispaterson** [comment] 2020-03-16 23:25
I can't replicate this...  See this commit https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/07f705d8a79420e5cc298b09c5c445eaca3b834a I am passing the vendor list JSON object as published from the lab.  I tried with both the GVL and TCModel https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/268d6d20df62458bacc97968a5c27aba17a9e4de 

But it doesn't seem to be reproduced.  Maybe you could paste the vendor list json that causes the problem?

**Comment by stefanrcint** [comment] 2020-03-17 07:39
I have downloaded and used this vendor list
https://vendorlist.consensu.org/v2/vendor-list.json

I tried setting up the TCModel directly like this (inspired by your example)
```
const {TCModel, TCString, GVL} = require('@iabtcf/core');
const vendorList = require('../vendorlist.json');
const tcModel = new TCModel(vendorList);
```
Then I get an encoding error instead:

```
Error [DecodingError]: Invalid Base64url Encoding
    at new t (C:\..\node_modules\@iabtcf\core\lib\errors\DecodingError.js:1:486)
    at Function.r.decode (C:\..\node_modules\@iabtcf\core\lib\encoder\Base64Url.js:1:714)
    at Function.e.decode (C:\..\node_modules\@iabtcf\core\lib\encoder\SegmentEncoder.js:1:932)
    at Function.e.decode (C:\..\node_modules\@iabtcf\core\lib\TCString.js:1:1284)
```


And have also tried this
```
const vendorList = require('../vendorlist.json');
GVL.baseUrl = "http://someplace.com";
const tcModel = new TCModel(new GVL(vendorList));
```
This fails with the following error message:
```
UnhandledPromiseRejectionWarning: GVLError: XMLHttpRequest is not defined
    at new t (C:\..r\node_modules\@iabtcf\core\lib\errors\GVLError.js:1:481)
    at C:\..\node_modules\@iabtcf\core\lib\GVL.js:1:3391
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:19176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**Comment by stefanrcint** [comment] 2020-03-17 07:47
For reference, this is how the entire stub is configured:

```
const vendorList = require('../vendorlist.json');
const tcModel = new TCModel(vendorList);

tcModel.vendorConsents.set(vendorIds || [1]);
tcModel.purposeConsents.set([IabPurposes.information_storage_and_access, IabPurposes.personalisation]);       

return TCString.encode(tcModel);
```

**Comment by chrispaterson** [comment] 2020-03-17 20:12
> Then I get an encoding error instead:
> 
> ```
> Error [DecodingError]: Invalid Base64url Encoding
>     at new t (C:\..\node_modules\@iabtcf\core\lib\errors\DecodingError.js:1:486)
>     at Function.r.decode (C:\..\node_modules\@iabtcf\core\lib\encoder\Base64Url.js:1:714)
>     at Function.e.decode (C:\..\node_modules\@iabtcf\core\lib\encoder\SegmentEncoder.js:1:932)
>     at Function.e.decode (C:\..\node_modules\@iabtcf\core\lib\TCString.js:1:1284)
> ```

That looks like a Decoding Error

> This fails with the following error message:
> 
> ```
> UnhandledPromiseRejectionWarning: GVLError: XMLHttpRequest is not defined
>     at new t (C:\..r\node_modules\@iabtcf\core\lib\errors\GVLError.js:1:481)
>     at C:\..\node_modules\@iabtcf\core\lib\GVL.js:1:3391
>     at processTicksAndRejections (internal/process/task_queues.js:85:5)
> (node:19176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error 
> ```

If you're using node you'll need to polyfill XMLHTTPRequest: https://www.npmjs.com/package/xmlhttprequest

**Comment by stefanrcint** [comment] 2020-03-18 09:37
Yes i try to decode the string later on to test for consent. So this is a more accurate workflow (a bit simplified, but the gist of it at least)

Set up stub and return an encoded tc string
```
const vendorList = require('../vendorlist.json');
const tcModel = new TCModel(vendorList);

tcModel.vendorConsents.set(vendorIds || [1]);
tcModel.purposeConsents.set([IabPurposes.information_storage_and_access, IabPurposes.personalisation]);       

return TCString.encode(tcModel);
```

Then I try to decode the string from the result of the above code and check consent like so:

```
const tcModel = TCString.decode(tc);

return tcModel.vendorConsents.has(this.config.tcVendorId) &&
        tcModel.purposeConsents.has(this.purposes.information_storage_and_access);
```

Not sure if it's the encoding or the decoding that is the problem though, but yes, the exception is thrown when doing `TCString.decode(tc)`

Let's ignore the XMLHTTPRequest issue, if I can create a TCModel by passing the vendor list like this I'll be a happy guy :)

**Comment by chrispaterson** [comment] 2020-03-18 15:24
Ok, I'll close this for now

**Closed by chrispaterson** 2020-03-18 15:24 UTC
Labels: Needs More, bug
